name: IPS-LAE
channels:
  - defaults
  - conda-forge
dependencies:
  - Python=3.11.5
  - numpy=1.24.3
  - pandas=2.0.3
  - scipy=1.11.1
  - bottleneck=1.3.5
  - scikit-learn=1.3.0
  - scikit-sparse =0.4.16
